name: 🐛 Bug Report
description: Report a bug in the KGV system
title: "fix: [Bug Summary] - [Affected Component]"
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        **Important**: Bug issues should focus on a single layer (Backend OR Frontend) and take maximum 1 day to fix.
        
        Please provide as much detail as possible to help us reproduce and fix the bug quickly.

  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Short, descriptive summary of the bug
      placeholder: e.g., "Aktenzeichen validation fails for valid format"
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: 🎯 Affected Component
      description: Which part of the system has the bug?
      options:
        - "Backend API (src/backend/KGV.WebApi/Controllers/)"
        - "Backend Business Logic (src/backend/KGV.Application/)"
        - "Backend Domain Logic (src/backend/KGV.Domain/) ⚠️"
        - "Backend Database (src/backend/KGV.Infrastructure/Persistence/)"
        - "Frontend UI (src/frontend/src/app/features/)"
        - "Frontend State Management (src/frontend/src/app/*/store/)"
        - "Frontend Forms/Validation (src/frontend/src/app/shared/validators/)"
        - "Integration (Backend ↔ Frontend API calls)"
        - "Authentication/Authorization (src/backend/KGV.Infrastructure/Identity/)"
        - "Other/Unknown"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - "🔥 Critical - System is unusable"
        - "🚨 High - Important feature is broken"
        - "📋 Medium - Feature works but has issues"
        - "📝 Low - Minor cosmetic issue"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📋 Detailed Description
      description: Provide a clear and detailed description of the bug
      placeholder: What exactly is wrong? What should happen instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should happen when you follow the steps above?
      placeholder: Describe the expected correct behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happens? Include any error messages
      placeholder: Describe what actually happens, including exact error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Provide details about your environment
      value: |
        - **Browser**: [e.g., Chrome 120, Firefox 121]
        - **Operating System**: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - **Screen Size**: [e.g., Desktop 1920x1080, Mobile 375x667]
        - **User Role**: [e.g., Admin, Sachbearbeiter, Bürger]
        - **API Version**: [if known]
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: 🔍 Console Errors/Logs
      description: Include any relevant console errors or server logs
      placeholder: |
        Paste any error messages from:
        - Browser Developer Console (F12)
        - Network tab errors
        - Server logs
        - Application logs
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots/Videos
      description: Add screenshots or videos that help explain the problem
      placeholder: |
        Drag and drop images here, or paste image URLs
        
        🎥 For complex bugs, consider recording a short video

  - type: checkboxes
    id: fix-tasks
    attributes:
      label: 🛠️ Fix Tasks (for assigned developer)
      description: Checklist for fixing this bug
      options:
        - label: "Reproduce the bug locally"
        - label: "Identify the root cause"
        - label: "Implement the fix"
        - label: "Add regression test to prevent reoccurrence"
        - label: "Verify fix doesn't break other functionality"
        - label: "Update documentation if needed"

  - type: dropdown
    id: estimated-fix-time
    attributes:
      label: 📊 Estimated Fix Time
      description: How long do you think this will take to fix?
      options:
        - "< 0.5 day (quick fix)"
        - "0.5 day (simple fix)"
        - "1 day (standard fix)"
        - "> 1 day (complex issue - may need breakdown)"
    validations:
      required: false

  - type: textarea
    id: related-issues
    attributes:
      label: 🔗 Related Issues
      description: Link any related bugs or issues
      placeholder: |
        - Related to #123
        - Duplicate of #456
        - Caused by #789

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other information that might help fix this bug
      placeholder: |
        - When did this start happening?
        - Is this a regression from a recent change?
        - Any workarounds you've found?
        - Business impact of this bug

  - type: checkboxes
    id: domain-impact
    attributes:
      label: 🛡️ Domain Model Impact
      description: Does this bug involve the protected domain model?
      options:
        - label: "⚠️ This bug affects domain model objects (requires domain approval for fixes)"
        - label: "✅ This is an application/infrastructure layer bug (normal fix process)"

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: "I have provided clear steps to reproduce the bug"
          required: true
        - label: "I have included all relevant error messages and screenshots"
          required: true
        - label: "I have specified the affected component accurately"
          required: true
        - label: "I have checked if this affects the protected domain model"
          required: true